name: Build and Test with Bazel
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: '0'
      - name: Download dependencies
        run: python3 utils/git-sync-deps
      - name: Mount Bazel cache
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ~/.bazel/cache
          key: bazel-cache-${{ runner.os }}
      - name: Build All
        run: bazel --output_user_root=~/.bazel/cache build //...
      - name: Test All
        run: bazel --output_user_root=~/.bazel/cache test //...
